import Head from 'next/head'

import { Inter } from 'next/font/google'

import { SiFauna } from "react-icons/si";
import{Icon} from "@chakra-ui/react"

export default function Home() {
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link 
          />
      </Head>
      <main>
       
      </main>
    </>
  )
}
